version: '2'
services:
    vanitytvml-mongodb:
        container_name: vanitytvml-mongodb
        image: mongo:3.2.3
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/VanityTVML/mongodb/:/data/db/
